# Generated by Django 5.0.4 on 2024-04-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BR', 'Brazilian'), ('US', 'American'), ('JP', 'Japanese'), ('IN', 'Indian'), ('FR', 'French'), ('RU', 'Russian'), ('CA', 'Canadian'), ('MX', 'Mexican'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('TR', 'Turkish'), ('UK', 'British'), ('AR', 'Argentinian')], max_length=100, null=True)),
            ],
        ),
    ]
